name: nsysu_ap
description: NSYSU AP

version: 1.2.0+10200

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  multiple_localization: ^0.3.0

  ap_common: ^0.21.2
  ap_common_firebase: ^0.15.0
  ap_common_plugin: 0.4.0
  #     path: ../ap_common_plugin

  #official plugin
  http: ^0.13.1
  html: ^0.15.0
  url_launcher: ^6.1.5

  #third party plugin
  encrypt: ^5.0.0
  sprintf: ^6.0.0
  crypto: ^3.0.1
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  flutter_inappwebview: ^5.4.3+7
  desktop_webview_window: ^0.1.6
  webview_windows: ^0.2.0
  timeago: ^3.0.2
  location: ^4.4.0
  google_sign_in_dartio: ^0.2.1
  firebase_core_desktop: ^1.0.1
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.8.2
  build_runner: ^2.1.5
  json_serializable: ^6.0.1

#dependency_overrides:
#  ap_common:
#    path: ../../GitHub-NKUST-ITC/ap_common
#  ap_common_firebase:
#    path: ../ap_common_firebase

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - changelog.json
    - assets/car_park_area.json

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: 'zh_TW'
  arb_dir: lib/l10n
  output_dir: lib/l10n
  use_deferred_loading: true