name: nsysu_ap
description: NSYSU AP

version: 1.0.1+10001

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ap_common: ^0.20.0
  ap_common_firebase: 0.13.0
  ap_common_plugin: 0.3.1
  #     path: ../ap_common_plugin

  #official plugin
  http: ^0.13.1
  html: ^0.15.0

  #third party plugin
  encrypt: ^5.0.0
  sprintf: ^6.0.0
  crypto: ^3.0.1
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  flutter_inappwebview: ^5.3.2
  timeago: ^3.0.2
  location: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

#dependency_overrides:
#  ap_common:
#    path: ../../GitHub-NKUST-ITC/ap_common
#  ap_common_firebase:
#    path: ../ap_common_firebase

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - changelog.json
    - assets/car_park_area.json
